export enum DistributionStep {
  CREATED = "CREATED",

  INSERTING_VOTE = "INSERTING_VOTE",
  VOTE_INSERTED = "VOTE_INSERTED",

  SENDING_TELEGRAM_MSG = "SENDING_TELEGRAM_MSG",
  TELEGRAM_MSG_SENT = "TELEGRAM_MSG_SENT",

  RESERVING_CHECKER = "RESERVING_CHECKER",
  CHECKER_RESERVED = "CHECKER_RESERVED",

  LINKING_CHECKER_TO_VOTE = "LINKING_CHECKER_TO_VOTE",
  CHECKER_TO_VOTE_LINKED = "CHECKER_TO_VOTE_LINKED",
}
