// Generated by Wrangler by running `wrangler types`

interface Env {
  ENVIRONMENT: "production" | "staging";
  CHKECERS_REMINDER_DURABLE_OBJECT: DurableObjectNamespace<
    import("./src/index").CheckersReminderDurableObject
  >;
}
