// Generated by `wrangler types` in the other workers; hand-maintained here until
// the bindings settle. Regenerate with `pnpm cf-typegen`.

interface ChatMessageDoc {
  chatId: string;
  messageId: number;
  messageThreadId: number | null;
  telegramId: string;
  telegramUsername: string | null;
  name: string | null;
  text: string;
  sentAt: Date | string;
  replyToMessageId: number | null;
  faqProcessedAt: Date | string | null;
  faqOutcome:
    | "answered"
    | "human-answered"
    | "not-a-question"
    | "no-match"
    | "low-confidence"
    | "duplicate"
    | "send-failed"
    | null;
  answeredWithFaqId: string | null;
}

interface Env {
  /* Workers AI, called through AI Gateway (see AI_GATEWAY_ID). */
  AI: Ai;

  /*
   * MongoDB, via the shared DB worker. Holds both the durable message log and
   * the sweep's working state (faqProcessedAt / faqOutcome) — there is no
   * separate buffer.
   */
  CHECKERS_DB_SERVICE: {
    upsertChatMessage(message: ChatMessageDoc): Promise<{ success: boolean; error?: string }>;
    findChatMessagesSince(
      chatId: string,
      sinceISO: string
    ): Promise<{ success: boolean; data?: ChatMessageDoc[]; error?: string }>;
    markChatMessageProcessed(
      chatId: string,
      messageId: number,
      outcome: NonNullable<ChatMessageDoc["faqOutcome"]>,
      faqId?: string | null,
      /* Overwrite an existing claim. Only for correcting this sweep's own record. */
      force?: boolean
      /* `claimed` is false when the message was already processed by someone else. */
    ): Promise<{ success: boolean; claimed?: boolean; error?: string }>;
  };

  /* KV — configuration only. */
  CHECKMATE_CHECKERS_PARAMETERS_KV: KVNamespace;

  /* Vars */
  AI_GATEWAY_ID: string;
  AI_MODEL: string;
  FAQ_SHADOW_MODE: string;
  /* Local only: enables POST /dev/classify. Never set in wrangler vars. */
  ENABLE_EVAL_ENDPOINT?: string;

  /* Secrets */
  TELEGRAM_ADMIN_BOT_TOKEN: string;
  TELEGRAM_ADMIN_WEBHOOK_SECRET: string;
  CHECKERS_CHAT_ID: string;
}
