// Generated by Wrangler by running `wrangler types`

interface Env {
  ENVIRONMENT: "production" | "staging";
  CHKECERS_PROGRAMME_DURABLE_OBJECT: DurableObjectNamespace<
    import("./src/index").CheckersProgrammeDurableObject
  >;
}
