// Generated by Wrangler by running `wrangler types`

interface Env {
  MONGODB_CONNECTION_STRING: string;
  ENVIRONMENT: "production" | "staging";
  DATABASE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").DatabaseDurableObject>;
}
