// lib/db/schema.ts
import { ObjectId } from "mongodb";

//NOSQL DATA TYPES

// Base document interface that all MongoDB documents extend
interface BaseDocument {
  _id?: ObjectId;
}

// Utility type to convert ObjectId fields to strings for API usage
type ObjectIdToString<T> = {
  [K in keyof T]: T[K] extends ObjectId
    ? string
    : T[K] extends ObjectId | null
      ? string | null
      : T[K] extends ObjectId | undefined
        ? string | undefined
        : T[K];
};

// API-compatible types - automatically derived from database types
export type CheckerAPI = ObjectIdToString<Checker>;
export type PollAPI = ObjectIdToString<Poll>;
export type VoteAPI = ObjectIdToString<Vote>;
export type ProgrammeAPI = ObjectIdToString<Programme>;
export type LeaderboardAPI = ObjectIdToString<Leaderboard>; // _id is the checkers Id
export type ChatMessageAPI = ObjectIdToString<ChatMessage>;

// User/Checker schema
export interface Checker extends BaseDocument {
  name: string | null; // The name of the Checker, set by them on onboarding
  telegramId: string; // The Telegram ID of the Checker
  telegramUsername: string | null; // The Telegram username of the Checker (without @)
  whatsappId: string | null; // The WhatsApp ID of the Checker
  singpassId: null; // The SingPass ID of the Checker (not used yet)
  isActive: boolean; // Whether the Checker is active and will be triggered
  isOnboardingComplete: boolean; // Whether the Checker has completed the onboarding process
  onboardingTime: Date | null; // The time the Checker completed the onboarding process
  isQuizComplete: boolean; // Whether the Checker has completed the onboarding quiz
  quizScore: number | null; // The score the Checker got in the quiz
  onboardingStatus: // The onboarding status of the Checker, either "name", "number", "otpSent", "verify", "quiz", "onboardWhatsapp", "joinGroupChat", "completed", or "offboarded"
    | "name"
    | "number"
    | "otpSent"
    | "verify"
    | "quiz"
    | "onboardWhatsapp"
    | "joinGroupChat"
    | "completed"
    | "offboarded";
  hasReceivedExtension: boolean; // Whether the Checker has received the extension for the program
  hasCompletedProgramme: boolean; // Whether the Checker has completed the programme
  certificateUrl: string | null; // The static URL of the Checker's certificate
  lastActivatedDate: Date | null; // The time the Checker last became active (for inactivity calculation)
  offboardingTime: Date | null; // The time the Checker was offboarded from the programme
  lastInactivityWarningSent: Date | null; // The time the 3-day inactivity warning was last sent
  numVoted: number; // The number of polls the Checker has voted on
  lastVotedTimestamp: Date | null; // The time the Checker last voted
  getNameMessageId: string | null; // The message ID of the message the Checker used to set their name
  dailyAssignmentCount: number; // The number of polls the Checker has been assigned to vote on today
  currentProgrammeId: ObjectId | null; // Reference to the active Programme, null if not enrolled
  // The checker's preferred daily number of vote assignments. Currently enforced
  // as a hard cap by the distributor (dailyAssignmentCount < targetDailyVotes);
  // the planned distribution rework will treat it as a target (topping up toward
  // it) rather than only a ceiling.
  targetDailyVotes: number;
}

// Message to be checked
export interface Poll extends BaseDocument {
  checkId: string; // CheckID from CheckMate AI platform
  text: string | null; // The text of the poll, if any
  imageUrl: string | null; // The URL of the image in the poll, if any
  caption: string | null; // The caption of the poll, if any
  longformResponse: Response; // The longform report generated by AI. Not needed for now
  shortformResponse: ShortformResponse; // The shortform report generated by AI. To be voted on
  humanResponse: HumanResponse; // The human-edited response
  isReport: boolean; // Whether the submission is a user-filed report rather than a regular check
  crowdSourcedCategory:
    | "scam"
    | "illicit"
    | "untrue"
    | "misleading"
    | "accurate"
    | "satire"
    | "spam"
    | "legitimate"
    | "irrelevant"
    | "unsure"
    | null; // The category of the poll, as determined by the crowd. Null means not yet determined
  crowdSourcedTruthScore: number | null; // TruthScore if the poll is info
  startedTimestamp: Date;
  assessedTimestamp: Date | null;
}

// Individual vote on a message
export interface Vote extends BaseDocument {
  pollId: ObjectId;
  checkerId: ObjectId;
  createdTimestamp: Date;
  votedTimestamp: Date | null;
  category: // The category of the message, either "scam", "illicit", "info", "satire", "spam", "legitimate", "irrelevant", "unsure", "pass". Null means not yet voted
    | "scam"
    | "illicit"
    | "info"
    | "satire"
    | "spam"
    | "legitimate"
    | "irrelevant"
    | "unsure"
    | "pass"
    | null;
  truthScore: 0 | 1 | 2 | 3 | 4 | 5 | null; // The truth score assigned to the message by the checker, on a 0-5 scale. Null means no truth score
  responseCategory: "great" | "acceptable" | "unacceptable" | null;
  commentOnResponse: string | null;
  responseTime: number | null; // Time taken to submit the vote in hours
  score: number | null; // Score awarded for this vote
  isCorrect: boolean | null; // Whether the vote matched the consensus
  showNoteAfterVote: boolean; // A/B test flag: true = show community note after voting, false = show before
  telegramMessageId: number | null; // The Telegram message ID for the vote notification (used to update button text after voting)
}

// Programme enrollment for a checker
export interface Programme extends BaseDocument {
  checkerId: ObjectId; // Reference to the Checker
  startDate: Date; // When the checker enrolled (onboarding completion)
  endDate: Date | null; // When the programme ended (completion/offboarding), null if active
  status: "active" | "completed" | "extended" | "offboarded" | "abandoned"; // Current programme status
  targets: {
    votes: number; // Target number of votes (e.g., 50)
    accuracy: number; // Target accuracy percentage (e.g., 60)
    reports: number; // Target number of reports (e.g., 10)
  };
  votesAtStart: number; // Snapshot of checker.numVoted at enrollment
  hasReceivedExtension: boolean; // Whether Day 60 extension notice was sent
  hasReceivedLowAccuracyWarning: boolean; // Whether low accuracy warning was sent
  certificateUrl: string | null; // URL to the generated certificate
  certificateName: string | null; // Name the checker chose to appear on the certificate
  completedAt: Date | null; // When the checker graduated
}

// OTHER TYPES
export interface Response {
  //format of the AI generated responses passed from CheckMate AI platform
  en: string | null;
  cn: string | null;
  links: string[] | null;
  timestamp: Date | null;
}

export interface ShortformResponse extends Response {
  downvoted: boolean;
}

export interface HumanResponse extends Response {
  updatedBy: string | null;
}

// Poll request to kick off the poll process, will be received via webhook from CheckMate AI platform
export interface PollRequest {
  checkId: string;
  imageUrl: string | null;
  caption: string | null;
  text: string | null;
  longformResponse: Response | null;
  shortformResponse: ShortformResponse | null;
  humanResponse: HumanResponse | null;
  isReport?: boolean;
}

// Message payload for poll update queue (sent to CheckMate platform when assessment changes)
export interface PollUpdateMessage {
  id: string; // checkId
  isHumanAssessed: boolean;
  crowdsourcedCategory: string | null;
  isCommunityNoteDownvoted: boolean;
}

//

// Database collections enum for type safety
export enum Collections {
  CHECKERS = "checkers",
  POLLS = "polls",
  VOTES = "votes",
  PROGRAMMES = "programmes",
}

// VoteChecker - join both Vote and Poll
export interface VoteChecker extends BaseDocument {
  pollId: ObjectId;
  checkerId: ObjectId;
  createdTimestamp: Date;
  votedTimestamp: Date | null;
  category: // The category of the message, either "scam", "illicit", "info", "satire", "spam", "legitimate", "irrelevant", "unsure", "pass". Null means not yet voted
    | "scam"
    | "illicit"
    | "info"
    | "satire"
    | "spam"
    | "legitimate"
    | "irrelevant"
    | "unsure"
    | "pass"
    | null;
  truthScore: 0 | 1 | 2 | 3 | 4 | 5 | null; // The truth score assigned to the message by the checker, on a 0-5 scale. Null means no truth score
  responseCategory: "great" | "acceptable" | "unacceptable" | null;
  commentOnResponse: string | null;
  responseTime: number | null; // Time taken to submit the vote in hours
  score: number | null; // Score awarded for this vote
  isCorrect: boolean | null; // Whether the vote matched the consensus
  poll: Poll;
}

// Leaderboard
export interface Leaderboard extends BaseDocument {
  checkerName: string; // Name from checkers collection
  numberOfVotes: number; // Total count of votes
  totalScore: number; // Sum of all scores
  averageResponseTime: number; // Average response time in hrs
  accuracy: number; // Percentage (0-100), rounded to 2 d.p.
  correctVotes: number; // Count of votes where isCorrect = true
}

export interface ProgrammeProgress {
  voteCount: number;
  accuracy: number | null;
  reportCount: number;
}

// Community group-chat message, captured by checkers-chat-management-service.
// Durable record for analysis (what do volunteers actually ask?), separate from
// the short-lived KV buffer that worker uses to decide what to answer.
export interface ChatMessage extends BaseDocument {
  chatId: string; // Telegram chat id, as a string (values exceed 2^53 in some chats)
  messageId: number; // Telegram message id, unique within the chat
  // Forum topic the message was posted in. Null means the General topic:
  // Telegram omits message_thread_id entirely there rather than sending a value.
  messageThreadId: number | null;
  telegramId: string; // Sender's Telegram user id
  telegramUsername: string | null; // Without @; absent for users who have no username
  name: string | null; // Sender's first_name, as a fallback label
  text: string;
  sentAt: Date; // Derived from Telegram's `date` (unix seconds)
  // Genuine reply target only. Telegram also points a topic's first message at
  // the forum_topic_created service message; that structural link is discarded
  // on ingest so it is never mistaken for someone answering a question.
  replyToMessageId: number | null;
  // When the FAQ sweep last considered this message. Null means not yet looked
  // at; this is what stops the sweep re-classifying the same message forever,
  // and it is the sweep's only piece of working state.
  faqProcessedAt: Date | null;
  // Why the sweep did or did not answer. "no-match" and "low-confidence" are
  // the interesting ones: together they are the list of questions volunteers
  // asked that the FAQ could not answer, i.e. the FAQ entries worth writing next.
  faqOutcome:
    | "answered"
    | "human-answered" // a colleague got there first; the bot stayed quiet
    | "not-a-question" // chatter that survived the cheap filters
    | "no-match"
    | "low-confidence"
    | "duplicate" // same FAQ already answered for someone else in that run
    | "send-failed"
    | null;
  // The FAQ id used, set only when faqOutcome is "answered".
  answeredWithFaqId: string | null;
}
