// lib/db/schema.ts
import { ObjectId } from 'mongodb';

//NOSQL DATA TYPES

// Base document interface that all MongoDB documents extend
interface BaseDocument {
  _id?: ObjectId;
}

// Utility type to convert ObjectId fields to strings for API usage
type ObjectIdToString<T> = {
  [K in keyof T]: T[K] extends ObjectId
    ? string
    : T[K] extends ObjectId | null
      ? string | null
      : T[K] extends ObjectId | undefined
        ? string | undefined
        : T[K];
};

// API-compatible types - automatically derived from database types
export type CheckerAPI = ObjectIdToString<Checker>;
export type PollAPI = ObjectIdToString<Poll>;
export type VoteAPI = ObjectIdToString<Vote>;
export type LeaderboardAPI = ObjectIdToString<Leaderboard> // _id is the checkers Id

// User/Checker schema
export interface Checker extends BaseDocument {
  name: string | null; // The name of the Checker, set by them on onboarding
  telegramId: string; // The Telegram ID of the Checker
  whatsappId: string | null; // The WhatsApp ID of the Checker
  singpassId: null; // The SingPass ID of the Checker (not used yet)
  isActive: boolean; // Whether the Checker is active and will be triggered
  isOnboardingComplete: boolean; // Whether the Checker has completed the onboarding process
  onboardingTime: Date | null; // The time the Checker completed the onboarding process
  isQuizComplete: boolean; // Whether the Checker has completed the onboarding quiz
  quizScore: number | null; // The score the Checker got in the quiz
  onboardingStatus: // The onboarding status of the Checker, either "name", "number", "otpSent", "verify", "quiz", "onboardWhatsapp", "joinGroupChat", "nlb", "completed", or "offboarded"
    | "name"
    | "number"
    | "otpSent"
    | "verify"
    | "quiz"
    | "onboardWhatsapp"
    | "joinGroupChat"
    | "nlb"
    | "completed"
    | "offboarded";
  hasReceivedExtension: boolean; // Whether the Checker has received the extension for the program
  hasCompletedProgramme: boolean; // Whether the Checker has completed the programme
  certificateUrl: string | null; // The static URL of the Checker's certificate
  lastActivatedDate: Date | null; // The time the Checker last became active (for inactivity calculation)
  offboardingTime: Date | null; // The time the Checker was offboarded from the programme
  lastInactivityWarningSent: Date | null; // The time the 3-day inactivity warning was last sent
  numVoted: number; // The number of polls the Checker has voted on
  lastVotedTimestamp: Date | null; // The time the Checker last voted
  getNameMessageId: string | null; // The message ID of the message the Checker used to set their name
  dailyAssignmentCount: Number; // The number of polls the Checker has been assigned to vote on today
}

// Message to be checked
export interface Poll extends BaseDocument {
  checkId: string; // CheckID from CheckMate AI platform
  text: string | null; // The text of the poll, if any
  imageURL: string | null; // The URL of the image in the poll, if any
  caption: string | null; // The caption of the poll, if any
  longformResponse: Response; // The longform report generated by AI. Not needed for now
  shortformResponse: ShortformResponse; // The shortform report generated by AI. To be voted on
  humanResponse: HumanResponse; // The human-edited response
  crowdSourcedCategory:
    | "scam"
    | "illicit"
    | "untrue"
    | "misleading"
    | "accurate"
    | "satire"
    | "spam"
    | "legitimate"
    | "irrelevant"
    | "unsure"
    | null; // The category of the poll, as determined by the crowd. Null means not yet determined
  crowdSourcedTruthScore: number | null; // TruthScore if the poll is info
  startedTimestamp: Date;
  assessedTimestamp: Date | null;
}

// Individual vote on a message
export interface Vote extends BaseDocument {
  pollId: ObjectId;
  checkerId: ObjectId;
  createdTimestamp: Date;
  votedTimestamp: Date | null;
  category: // The category of the message, either "scam", "illicit", "info", "satire", "spam", "legitimate", "irrelevant", "unsure", "pass". Null means not yet voted
    | "scam"
    | "illicit"
    | "info"
    | "satire"
    | "spam"
    | "legitimate"
    | "irrelevant"
    | "unsure"
    | "pass"
    | null;
  truthScore: 0 | 1 | 2 | 3 | 4 | 5 | null; // The truth score assigned to the message by the checker, on a 0-5 scale. Null means no truth score
  responseCategory: "great" | "acceptable" | "unacceptable" | null;
  commentOnResponse: string | null;
  responseTime: number | null; // Time taken to submit the vote in hours
  score: number | null; // Score awarded for this vote
  isCorrect: boolean | null; // Whether the vote matched the consensus
  showNoteAfterVote: boolean; // A/B test flag: true = show community note after voting, false = show before
}

// OTHER TYPES
export interface Response {
  //format of the AI generated responses passed from CheckMate AI platform
  en: string | null;
  cn: string | null;
  links: string[] | null;
  timestamp: Date | null;
}

export interface ShortformResponse extends Response {
  downvoted: boolean;
}

export interface HumanResponse extends Response {
  updatedBy: string | null;
}

// Poll request to kick off the poll process, will be received via webhook from CheckMate AI platform
export interface PollRequest {
  checkId: string;
  imageUrl: string | null;
  caption: string | null;
  text: string | null;
  longformResponse: Response | null;
  shortformResponse: ShortformResponse | null;
  humanResponse: HumanResponse | null;
}

// Message payload for poll update queue (sent to CheckMate platform when assessment changes)
export interface PollUpdateMessage {
  id: string; // checkId
  isHumanAssessed: boolean;
  crowdsourcedCategory: string | null;
  isCommunityNoteDownvoted: boolean;
}

//

// Database collections enum for type safety
export enum Collections {
  CHECKERS = "checkers",
  POLLS = "polls",
  VOTES = "votes",
}

// VoteChecker - join both Vote and Poll
export interface VoteChecker extends BaseDocument {
  pollId: ObjectId;
  checkerId: ObjectId;
  createdTimestamp: Date;
  votedTimestamp: Date | null;
  category: // The category of the message, either "scam", "illicit", "info", "satire", "spam", "legitimate", "irrelevant", "unsure", "pass". Null means not yet voted
    | "scam"
    | "illicit"
    | "info"
    | "satire"
    | "spam"
    | "legitimate"
    | "irrelevant"
    | "unsure"
    | "pass"
    | null;
  truthScore: 0 | 1 | 2 | 3 | 4 | 5 | null; // The truth score assigned to the message by the checker, on a 0-5 scale. Null means no truth score
  responseCategory: "great" | "acceptable" | "unacceptable" | null;
  commentOnResponse: string | null;
  responseTime: number | null; // Time taken to submit the vote in hours
  score: number | null; // Score awarded for this vote
  isCorrect: boolean | null; // Whether the vote matched the consensus
  poll: Poll;
}

// Leaderboard
export interface Leaderboard extends BaseDocument {
  checkerName: string; // Name from checkers collection
  numberOfVotes: number;  // Total count of votes 
  totalScore: number; // Sum of all scores 
  averageResponseTime: number; // Average response time in hrs
  accuracy: number; // Percentage (0-100), rounded to 2 d.p.
  correctVotes: number; // Count of votes where isCorrect = true 
}

