/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: b739a9c19cff1463949c4db47674ed86)
// Runtime types generated with workerd@1.20251217.0 2025-12-24

interface WhatsAppCheckerHandlerService {
  checkUser(whatsappId: string): Promise<{ exists: boolean }>;
}

interface WhatsAppAdhocMessage {
  whatsappId: string;
  messageType: "otp" | string;
  content: {
    otp?: string;
    [key: string]: unknown;
  };
  metadata: {
    source: string;
    [key: string]: unknown;
  };
}

interface Env {
  // KV Namespaces
  OTP_KV: KVNamespace;
  CHECKMATE_CHECKERS_PARAMETERS_KV: KVNamespace;

  // Service Bindings
  CHECKERS_DB_SERVICE: CheckersDbService;
  CHECKER_REMINDER_ALARM_SERVICE: CheckerReminderAlarmService;

  // Environment Variables
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  TELEGRAM_ADMIN_BOT_TOKEN: string;
  CHECKERS_CHAT_ID: string;
  HOST_URL: string;
  TYPEFORM_URL: string;
  WHATSAPP_BOT_LINK: string;
  CHECKERS_GROUP_LINK: string;
  ENVIRONMENT?: string;
  WHATSAPP_ADHOC_MESSAGE_QUEUE: Queue<WhatsAppAdhocMessage>;
  WHATSAPP_MESSAGE_SERVICE: WhatsAppMessageService;
  TYPEFORM_SECRET_TOKEN: string;
  WHATSAPP_CHECKER_HANDLER_SERVICE: WhatsAppCheckerHandlerService;
  API_KEY: string;
  CHECKERS_EVENTS_QUEUE: Queue<unknown>;
}
